#!/usr/bin/env bash
# TensorCash native launcher for hosted GPU containers without a Docker daemon.
#
# This script intentionally uses the public TensorCash source tree and the
# public, checksum-pinned controller release.  It does not contain or fetch a
# Rust source checkout.  All generated/runtime files live under runtime/native
# and can be deleted with `bash native-vast.sh --purge-runtime`.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
config="${MINER_CONFIG:-$script_dir/miner.env}"
pool_arg=""
wallet_arg=""
worker_arg=""
gpu_arg=""
install_only=false
stop_only=false
logs_only=false
status_only=false
plan_only=false
purge_only=false
rebuild=false

readonly TENSORCASH_SOURCE_URL="${TENSORCASH_SOURCE_URL:-https://github.com/tensorcash/tensorcash.git}"
readonly TENSORCASH_SOURCE_REF="${TENSORCASH_SOURCE_REF:-2df1b0192b8323b1e92699de5f7c0c09c9c5e02a}"

usage() {
  cat <<'EOF'
Usage:
  bash native-vast.sh --pool HOST:PORT --wallet PAYOUT --worker NAME [--gpu INDEX]
  bash native-vast.sh --install
  bash native-vast.sh --plan | --stop | --status | --logs | --purge-runtime

This is for Vast/RunPod-style containers that expose NVIDIA devices but have
no Docker daemon. Native mode runs one TP=1 miner instance for every selected
>=22 GiB GPU. Instances share one downloaded model/runtime, but use isolated
ports, PIDs, logs, proof data, and worker labels. It is independent from
start.sh's Docker mode.
EOF
}

fail() {
  echo "ERROR: $*" >&2
  exit 2
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "Missing required command: $1"
}

positive_integer() {
  local value="$1" name="$2"
  [[ "$value" =~ ^[1-9][0-9]*$ ]] || fail "$name must be a positive integer."
}

fraction_in_range() {
  local value="$1" name="$2" minimum="$3" maximum="$4"
  [[ "$value" =~ ^([0-9]+)(\.[0-9]+)?$ ]] || fail "$name must be a decimal number."
  awk -v value="$value" -v minimum="$minimum" -v maximum="$maximum" \
    'BEGIN { exit !(value >= minimum && value <= maximum) }' || \
    fail "$name must be between $minimum and $maximum."
}

curl_retry_args() {
  if curl --help all 2>/dev/null | grep -q -- '--retry-all-errors'; then
    printf '%s\n' '--retry-all-errors'
  fi
}

download_file() {
  local url="$1" output="$2"
  local -a proxy_args=() retry_args=()
  [[ -n "${TENSORCASH_HTTP_PROXY:-}" ]] && proxy_args=(--proxy "$TENSORCASH_HTTP_PROXY")
  mapfile -t retry_args < <(curl_retry_args)
  curl --fail --location --retry 8 "${retry_args[@]}" --connect-timeout 30 \
    --speed-time 90 --speed-limit 10240 "${proxy_args[@]}" --output "$output" "$url"
}

ensure_compatible_miner_binary() {
  local binary_dir="$script_dir/runtime/bin"
  local binary_path="$binary_dir/niuquanminer"
  local binary_url="${TENSORCASH_CONTROLLER_URL:-https://github.com/Avalonbtc/tensorcash-miner-launcher/releases/download/controller-glibc235-v9/niuquanminer-linux-amd64-glibc235}"
  local expected_sha256="${TENSORCASH_CONTROLLER_SHA256:-88fad32fd31782bb9f9dd6ddca516ef7dfb023ecdc349949ac976c3428220c4a}"
  local temporary

  require_command curl
  require_command sha256sum
  [[ "$binary_url" =~ ^https?:// ]] || fail "TENSORCASH_CONTROLLER_URL must be an HTTP(S) URL."
  [[ "$expected_sha256" =~ ^[A-Fa-f0-9]{64}$ ]] || fail "TENSORCASH_CONTROLLER_SHA256 must be a SHA-256 digest."
  mkdir -p "$binary_dir"
  chmod 700 "$binary_dir"
  if [[ -x "$binary_path" ]] && printf '%s  %s\n' "$expected_sha256" "$binary_path" | sha256sum -c - >/dev/null 2>&1; then
    echo "Using verified TensorCash controller: $binary_path"
    return 0
  fi

  temporary="$binary_dir/.niuquanminer.$$"
  rm -f "$temporary"
  echo "Downloading checksum-pinned TensorCash controller (about 3 MB)..."
  download_file "$binary_url" "$temporary" || { rm -f "$temporary"; fail "Could not download TensorCash controller."; }
  printf '%s  %s\n' "$expected_sha256" "$temporary" | sha256sum -c - || { rm -f "$temporary"; fail "Controller checksum mismatch."; }
  chmod 755 "$temporary"
  mv -f "$temporary" "$binary_path"
  echo "Installed verified TensorCash controller."
}

write_initial_config() {
  [[ -n "$pool_arg" && -n "$wallet_arg" && -n "$worker_arg" ]] || {
    usage
    fail "First launch requires --pool, --wallet, and --worker."
  }
  [[ "$pool_arg" =~ ^[A-Za-z0-9.-]+:[1-9][0-9]{0,4}$ ]] || fail "--pool must be HOST:PORT."
  [[ "$wallet_arg" =~ ^[A-Za-z0-9._:-]+$ ]] || fail "--wallet contains unsupported characters."
  [[ "$worker_arg" =~ ^[A-Za-z0-9._-]+$ ]] || fail "--worker contains unsupported characters."
  [[ -z "$gpu_arg" || "$gpu_arg" == all || "$gpu_arg" =~ ^[0-9]+$ ]] || \
    fail "--gpu must be an NVIDIA GPU index or all."

  local token gpu
  token="$(od -An -N32 -tx1 /dev/urandom | tr -d ' \n')"
  gpu="${gpu_arg:-all}"
  umask 077
  cat > "$config" <<EOF
# Generated by native-vast.sh. Do not publish this file.
POOL_HOST=${pool_arg%:*}
POOL_PORT=${pool_arg##*:}
PAYOUT_ACCOUNT=$wallet_arg
WORKER=$worker_arg
NOMP_SIDECAR_TOKEN=$token
MODEL_NAME=Qwen/Qwen3-8B
MODEL_COMMIT=9c925d64d72725edaf899c6cb9c377fd0709d9c5
MODEL_DIFFICULTY_NORMALIZER=1000000
MAX_MODEL_LEN=2048
# Shared default across native and Docker modes. Startup capacity probing is
# retained as a hard safety gate for every VRAM tier and TP topology.
GPU_MEM_UTIL=0.89
# Starts at 32 and probes upward until real vLLM admission, sustained generation,
# or a request error rejects the next level. Set mode=manual for a fixed benchmark.
TENSORCASH_CONCURRENCY_MODE=auto
TENSORCASH_AUTO_CONCURRENCY_START=32
TENSORCASH_AUTO_CONCURRENCY_STEP=32
# 1024 is an engineering circuit breaker, not a GPU-memory tier cap.
TENSORCASH_AUTO_CONCURRENCY_CEILING=1024
# `auto` selects every >=22 GiB card. Set a comma-separated list such as
# `0,2,5` to select only particular cards. --gpu INDEX writes that one card.
TENSORCASH_NATIVE_GPU_GROUPS=$gpu
MODELS_DATA=$script_dir/runtime/models
RUNTIME_DATA=$script_dir/runtime/data
TENSORCASH_POLL_MS=200
TENSORCASH_SUBMIT_WINDOW=16
TENSORCASH_STATS_INTERVAL=30
TENSORCASH_SIDECAR_WAIT_SECONDS=1200
TENSORCASH_MODEL_DOWNLOAD_ATTEMPTS=12
TENSORCASH_MODEL_DOWNLOAD_DELAY_SECONDS=15
EOF
  chmod 600 "$config"
  echo "Created private miner config: $config"
}

load_config() {
  [[ -f "$config" ]] || write_initial_config
  set -a
  # shellcheck disable=SC1090
  source "$config"
  set +a

  # Older native configs predate bounded parallel pool submission. Keep those
  # installations compatible while the controller enforces the same upper cap.
  TENSORCASH_SUBMIT_WINDOW="${TENSORCASH_SUBMIT_WINDOW:-16}"

  [[ "${POOL_HOST:-}" =~ ^[A-Za-z0-9.-]+$ && "${POOL_PORT:-}" =~ ^[1-9][0-9]{0,4}$ ]] || fail "Invalid pool settings in miner.env."
  [[ "${PAYOUT_ACCOUNT:-}" =~ ^[A-Za-z0-9._:-]+$ ]] || fail "Invalid payout account in miner.env."
  [[ "${WORKER:-}" =~ ^[A-Za-z0-9._-]+$ ]] || fail "Invalid worker in miner.env."
  [[ "${NOMP_SIDECAR_TOKEN:-}" =~ ^[A-Fa-f0-9]{32,}$ ]] || fail "Invalid NOMP_SIDECAR_TOKEN in miner.env."
  [[ "${MODEL_NAME:-}" == "Qwen/Qwen3-8B" ]] || fail "Native launcher currently supports the pinned Qwen/Qwen3-8B TensorCash profile only."
  [[ "${MODEL_COMMIT:-}" == "9c925d64d72725edaf899c6cb9c377fd0709d9c5" ]] || fail "MODEL_COMMIT must be the chain-pinned TensorCash Qwen3-8B revision."
  positive_integer "${MODEL_DIFFICULTY_NORMALIZER:-0}" MODEL_DIFFICULTY_NORMALIZER
  positive_integer "${MAX_MODEL_LEN:-0}" MAX_MODEL_LEN
  positive_integer "${TENSORCASH_SUBMIT_WINDOW:-0}" TENSORCASH_SUBMIT_WINDOW
  TENSORCASH_CONCURRENCY_MODE="${TENSORCASH_CONCURRENCY_MODE:-auto}"
  TENSORCASH_AUTO_CONCURRENCY_START="${TENSORCASH_AUTO_CONCURRENCY_START:-32}"
  TENSORCASH_AUTO_CONCURRENCY_STEP="${TENSORCASH_AUTO_CONCURRENCY_STEP:-32}"
  TENSORCASH_AUTO_CONCURRENCY_CEILING="${TENSORCASH_AUTO_CONCURRENCY_CEILING:-1024}"
  case "$TENSORCASH_CONCURRENCY_MODE" in
    auto)
      positive_integer "$TENSORCASH_AUTO_CONCURRENCY_START" TENSORCASH_AUTO_CONCURRENCY_START
      positive_integer "$TENSORCASH_AUTO_CONCURRENCY_STEP" TENSORCASH_AUTO_CONCURRENCY_STEP
      (( TENSORCASH_AUTO_CONCURRENCY_STEP <= 256 )) || \
        fail "TENSORCASH_AUTO_CONCURRENCY_STEP must not exceed 256."
      positive_integer "$TENSORCASH_AUTO_CONCURRENCY_CEILING" TENSORCASH_AUTO_CONCURRENCY_CEILING
      (( TENSORCASH_AUTO_CONCURRENCY_CEILING <= 1024 )) || \
        fail "TENSORCASH_AUTO_CONCURRENCY_CEILING must not exceed 1024."
      ;;
    manual)
      positive_integer "${VLLM_MAX_NUM_SEQS:-0}" VLLM_MAX_NUM_SEQS
      positive_integer "${NOMP_SIDECAR_CONCURRENCY:-0}" NOMP_SIDECAR_CONCURRENCY
      positive_integer "${NOMP_SIDECAR_MIN_BUFFERED_PROOFS:-0}" NOMP_SIDECAR_MIN_BUFFERED_PROOFS
      positive_integer "${NOMP_SIDECAR_MAX_BUFFERED_PROOFS:-0}" NOMP_SIDECAR_MAX_BUFFERED_PROOFS
      (( NOMP_SIDECAR_CONCURRENCY <= VLLM_MAX_NUM_SEQS )) || \
        fail "NOMP_SIDECAR_CONCURRENCY must not exceed VLLM_MAX_NUM_SEQS."
      (( NOMP_SIDECAR_CONCURRENCY <= 1024 )) || \
        fail "Native TensorCash manual concurrency must not exceed 1024."
      ;;
    *) fail "TENSORCASH_CONCURRENCY_MODE must be auto or manual." ;;
  esac
  if [[ -n "${NOMP_SIDECAR_ADMISSION_SPREAD_MS:-}" ]]; then
    [[ "$NOMP_SIDECAR_ADMISSION_SPREAD_MS" =~ ^[0-9]+$ ]] || \
      fail "NOMP_SIDECAR_ADMISSION_SPREAD_MS must be a non-negative integer."
    (( NOMP_SIDECAR_ADMISSION_SPREAD_MS <= 2000 )) || \
      fail "NOMP_SIDECAR_ADMISSION_SPREAD_MS must not exceed 2000."
  fi
  if [[ -n "${NOMP_SIDECAR_PREFETCH_REQUESTS:-}" ]]; then
    [[ "$NOMP_SIDECAR_PREFETCH_REQUESTS" =~ ^[0-9]+$ ]] || \
      fail "NOMP_SIDECAR_PREFETCH_REQUESTS must be a non-negative integer."
    (( NOMP_SIDECAR_PREFETCH_REQUESTS <= 64 )) || \
      fail "NOMP_SIDECAR_PREFETCH_REQUESTS must not exceed 64."
  fi
  fraction_in_range "${GPU_MEM_UTIL:-}" GPU_MEM_UTIL 0.50 0.95
  if [[ "$TENSORCASH_CONCURRENCY_MODE" == manual ]]; then
    (( NOMP_SIDECAR_MIN_BUFFERED_PROOFS <= NOMP_SIDECAR_MAX_BUFFERED_PROOFS )) || \
      fail "NOMP_SIDECAR_MIN_BUFFERED_PROOFS must not exceed NOMP_SIDECAR_MAX_BUFFERED_PROOFS."
  fi
  (( TENSORCASH_SUBMIT_WINDOW <= 64 )) || fail "TENSORCASH_SUBMIT_WINDOW must not exceed 64."
  # Existing single-GPU native configs did not contain this key. Upgrade them
  # to `auto`: one-card hosts behave exactly as before, while a multi-card
  # 24/48 GiB host can use every independently viable GPU.
  TENSORCASH_NATIVE_GPU_GROUPS="${TENSORCASH_NATIVE_GPU_GROUPS:-auto}"
  [[ "$TENSORCASH_NATIVE_GPU_GROUPS" == auto || "$TENSORCASH_NATIVE_GPU_GROUPS" == all || \
     "$TENSORCASH_NATIVE_GPU_GROUPS" =~ ^[0-9]+(,[0-9]+)*$ ]] || \
    fail "TENSORCASH_NATIVE_GPU_GROUPS must be auto, all, or comma-separated GPU indices."
}

native_paths() {
  NATIVE_HOME="${TENSORCASH_NATIVE_HOME:-$script_dir/runtime/native}"
  NATIVE_VENV="$NATIVE_HOME/venv"
  NATIVE_SOURCE="$NATIVE_HOME/tensorcash-source"
  NATIVE_PROXY="$NATIVE_HOME/miner-proxy/src"
  NATIVE_BUILD="$NATIVE_HOME/build"
  NATIVE_INSTANCES="$NATIVE_HOME/instances"
  NATIVE_MARKER="$NATIVE_HOME/.runtime-ready"
  NATIVE_PY="$NATIVE_VENV/bin/python"
  NATIVE_VLLM="$NATIVE_VENV/bin/vllm"
}

native_instance_paths() {
  local instance="$1"
  NATIVE_INSTANCE="$instance"
  NATIVE_INSTANCE_HOME="$NATIVE_INSTANCES/$instance"
  NATIVE_LOGS="$NATIVE_INSTANCE_HOME/logs"
  NATIVE_PIDS="$NATIVE_INSTANCE_HOME/pids"
  NATIVE_INSTANCE_ENV="$NATIVE_INSTANCE_HOME/runtime.env"
}

native_capacity_file() {
  local gpu_name="$1" memory="$2" fingerprint
  # Cards with the same model/VRAM/runtime profile can reuse the first card's
  # measured capacity. A failed reuse falls back to normal vLLM discovery.
  fingerprint="${gpu_name}|${memory}|${MODEL_COMMIT}|${GPU_MEM_UTIL}|${TENSORCASH_AUTO_CONCURRENCY_CEILING}"
  fingerprint="$(printf '%s' "$fingerprint" | sha256sum | awk '{print $1}')"
  printf '%s/capacity-%s.txt\n' "$NATIVE_HOME/capacity" "$fingerprint"
}

native_port_available() {
  local port="$1"
  "$NATIVE_PY" - "$port" <<'PY'
import socket
import sys

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
try:
    sock.bind(("127.0.0.1", int(sys.argv[1])))
except OSError:
    raise SystemExit(1)
finally:
    sock.close()
PY
}

native_allocate_instance_ports() {
  local instance_number="$1" offset="$((instance_number - 1))"
  local default_offset="$offset" vllm sidecar collector reserved
  for ((; offset < 2048; offset += 1)); do
    vllm="$((8000 + offset))"
    sidecar="$((8080 + offset))"
    collector="$((7002 + offset))"
    (( collector <= 65535 )) || break
    reserved=" ${NATIVE_RESERVED_PORTS:-} "
    [[ "$reserved" == *" $vllm "* || "$reserved" == *" $sidecar "* || "$reserved" == *" $collector "* ]] && continue
    native_port_available "$vllm" || continue
    native_port_available "$sidecar" || continue
    native_port_available "$collector" || continue
    NATIVE_VLLM_PORT="$vllm"
    NATIVE_SIDECAR_PORT="$sidecar"
    NATIVE_COLLECTOR_PORT="$collector"
    NATIVE_RESERVED_PORTS="${NATIVE_RESERVED_PORTS:-} $vllm $sidecar $collector"
    if (( offset != default_offset )); then
      echo "Native g$instance_number bypasses occupied default ports; using vLLM=$vllm sidecar=$sidecar proof=$collector." >&2
    fi
    return 0
  done
  fail "Could not allocate an isolated local port triplet for native group g$instance_number."
}

resolve_native_gpu_indices() {
  local requested="$TENSORCASH_NATIVE_GPU_GROUPS" count index memory
  local -a selected=()
  count="$(nvidia-smi --query-gpu=index --format=csv,noheader | wc -l | tr -d '[:space:]')"
  [[ "$count" =~ ^[1-9][0-9]*$ ]] || fail "No NVIDIA GPUs are visible to nvidia-smi."

  if [[ "$requested" == auto || "$requested" == all ]]; then
    for ((index = 0; index < count; index += 1)); do
      memory="$(nvidia-smi --id="$index" --query-gpu=memory.total --format=csv,noheader,nounits | tr -d '[:space:]')"
      [[ "$memory" =~ ^[0-9]+$ ]] || fail "GPU $index is not visible to nvidia-smi."
      if (( memory >= ${TENSORCASH_NATIVE_MIN_VRAM_MIB:-22000} )); then
        selected+=("$index")
      else
        echo "Native auto planner leaves GPU $index idle (${memory} MiB < ${TENSORCASH_NATIVE_MIN_VRAM_MIB:-22000} MiB TP=1 minimum)." >&2
      fi
    done
  else
    IFS=',' read -r -a selected <<< "$requested"
  fi

  ((${#selected[@]} > 0)) || fail "No native TensorCash GPU has enough VRAM for TP=1."
  declare -A seen=()
  for index in "${selected[@]}"; do
    [[ "$index" =~ ^[0-9]+$ ]] && (( index < count )) || fail "GPU $index is not visible to nvidia-smi."
    [[ -z "${seen[$index]:-}" ]] || fail "GPU $index appears more than once in TENSORCASH_NATIVE_GPU_GROUPS."
    seen[$index]=1
    memory="$(nvidia-smi --id="$index" --query-gpu=memory.total --format=csv,noheader,nounits | tr -d '[:space:]')"
    (( memory >= ${TENSORCASH_NATIVE_MIN_VRAM_MIB:-22000} )) || \
      fail "Native TP=1 needs >=${TENSORCASH_NATIVE_MIN_VRAM_MIB:-22000} MiB VRAM; GPU $index exposes ${memory} MiB."
  done
  printf '%s\n' "${selected[@]}"
}

configure_native_auto_concurrency() {
  local cap start prefetch prefetch_raw required_buffer
  # Native mode is TP=1. Do not impose a VRAM-tier concurrency cap: vLLM's
  # actual admission and sustained generation choose the useful level.
  cap="$TENSORCASH_AUTO_CONCURRENCY_CEILING"
  start="$TENSORCASH_AUTO_CONCURRENCY_START"
  (( start <= cap )) || start="$cap"
  # Keep a 25% vLLM waiting reserve, mirroring the production profile of
  # 128 running / 32 waiting requests. These requests wait in vLLM and do
  # not consume additional running KV slots, but they prevent fixed-length
  # cohorts from leaving the GPU empty while aiohttp refills the sidecar.
  prefetch_raw="${NOMP_SIDECAR_PREFETCH_REQUESTS:-auto}"
  if [[ "$prefetch_raw" == "auto" ]]; then
    prefetch="$(( (cap + 3) / 4 ))"
    (( prefetch <= 64 )) || prefetch=64
  else
    prefetch="$prefetch_raw"
    [[ "$prefetch" =~ ^[0-9]+$ ]] || fail "NOMP_SIDECAR_PREFETCH_REQUESTS must be auto or a non-negative integer."
  fi

  VLLM_MAX_NUM_SEQS="$cap"
  NOMP_SIDECAR_CONCURRENCY=auto
  NOMP_SIDECAR_ADAPTIVE_START_CONCURRENCY="$start"
  NOMP_SIDECAR_ADAPTIVE_MAX_CONCURRENCY="$cap"
  NOMP_SIDECAR_ADAPTIVE_STEP="$TENSORCASH_AUTO_CONCURRENCY_STEP"
  NOMP_SIDECAR_PREFETCH_REQUESTS="$prefetch"
  VLLM_CUDA_GRAPH_SIZES="$(vllm_cuda_graph_sizes "$cap")"
  # A 24 GiB TP=1 card has sufficient activation headroom for the same 8192
  # token scheduler budget used by the validated BobLabs 24 GiB profile. It
  # is independent of the 2048-token context guard used by proof requests.
  VLLM_MAX_NUM_BATCHED_TOKENS=8192
  NOMP_SIDECAR_MIN_BUFFERED_PROOFS="$(( start > 4 ? start / 2 : 2 ))"
  NOMP_SIDECAR_MAX_BUFFERED_PROOFS="$(( cap * 2 ))"
  (( NOMP_SIDECAR_MAX_BUFFERED_PROOFS <= 512 )) || NOMP_SIDECAR_MAX_BUFFERED_PROOFS=512
  required_buffer="$(( cap + prefetch ))"
  (( required_buffer <= 512 )) || required_buffer=512
  (( NOMP_SIDECAR_MAX_BUFFERED_PROOFS >= required_buffer )) || \
    fail "Native auto proof buffer cannot cover the configured NOMP_SIDECAR_PREFETCH_REQUESTS."
}

vllm_cuda_graph_sizes() {
  local max_seqs="$1" size
  local -a sizes=(1 2 4 8 16 32 64 96 128 160 192 224 256 320 384 448 512 640 768 896 1024)
  local -a applicable=()
  for size in "${sizes[@]}"; do
    (( size <= max_seqs )) && applicable+=("$size")
  done
  (IFS=,; printf '%s' "${applicable[*]}")
}

as_root() {
  if ((EUID == 0)); then
    "$@"
  else
    require_command sudo
    sudo "$@"
  fi
}

install_system_packages() {
  [[ "${TENSORCASH_NATIVE_SKIP_APT:-false}" =~ ^(1|true|yes)$ ]] && return 0
  require_command apt-get
  echo "Installing native TensorCash build/runtime dependencies..."
  as_root apt-get update
  as_root env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    python3.10 python3.10-venv python3.10-dev python3-pip \
    build-essential cmake git curl wget unzip rsync patch pkg-config \
    nasm yasm libtool autoconf automake m4 \
    libboost-all-dev libflint-dev libgmp-dev libzmq3-dev \
    libssl-dev libcrypto++-dev libargon2-dev libargon2-1 ca-certificates
}

sync_tensorcash_source() {
  if [[ ! -d "$NATIVE_SOURCE/.git" ]] || [[ "$(git -C "$NATIVE_SOURCE" rev-parse HEAD 2>/dev/null || true)" != "$TENSORCASH_SOURCE_REF" ]]; then
    echo "Fetching public TensorCash source at $TENSORCASH_SOURCE_REF..."
    rm -rf "$NATIVE_SOURCE"
    mkdir -p "$NATIVE_SOURCE"
    git -C "$NATIVE_SOURCE" init -q
    git -C "$NATIVE_SOURCE" remote add origin "$TENSORCASH_SOURCE_URL"
    git -C "$NATIVE_SOURCE" fetch -q --depth 1 origin "$TENSORCASH_SOURCE_REF"
    git -C "$NATIVE_SOURCE" checkout -q --detach FETCH_HEAD
  fi
  [[ "$(git -C "$NATIVE_SOURCE" rev-parse HEAD)" == "$TENSORCASH_SOURCE_REF" ]] || fail "TensorCash source ref did not resolve to the pinned commit."

  # vllm-v010 is a pinned Git submodule, not a directory contained in the
  # parent commit.  A plain shallow fetch leaves an empty mount point and then
  # fails later at rsync.  Fetch only this required submodule; bcore/llama and
  # the other large submodules are not part of native mining startup.
  git -C "$NATIVE_SOURCE" submodule sync -- services/miner-api/vllm-v010
  git -C "$NATIVE_SOURCE" submodule update --init --depth 1 services/miner-api/vllm-v010
  [[ -d "$NATIVE_SOURCE/services/miner-api/vllm-v010/vllm" ]] || \
    fail "TensorCash vLLM v0.10 submodule is unavailable after checkout."
}

prepare_python_runtime() {
  if [[ ! -x "$NATIVE_PY" ]]; then
    python3.10 -m venv "$NATIVE_VENV"
  fi
  "$NATIVE_PY" -m pip install --upgrade pip wheel 'setuptools<81'
  "$NATIVE_PY" -m pip install --no-cache-dir -r "$NATIVE_SOURCE/services/miner-api/requirements_v10.txt"
  "$NATIVE_PY" -m pip install --no-cache-dir -r "$NATIVE_SOURCE/services/miner-api/proxy_requirements.txt"
  "$NATIVE_PY" -m pip install --no-cache-dir numpy pybind11
}

repair_stock_vllm_if_needed() {
  local site_packages flash_layers
  site_packages="$($NATIVE_PY -c 'import site; print(site.getsitepackages()[0])')"
  flash_layers="$site_packages/vllm/vllm_flash_attn/layers"

  # TensorCash carries a pure-Python fork over the stock vLLM 0.10 wheel.  The
  # wheel itself owns vllm_flash_attn and vllm._version; neither exists in the
  # fork.  Older native-launcher builds used rsync --delete and removed them.
  # Restore only the pinned wheel (without re-resolving all CUDA dependencies)
  # before applying the overlay, so rerunning the launcher repairs that state.
  if [[ ! -d "$flash_layers" ]] || [[ ! -f "$site_packages/vllm/_version.py" ]]; then
    echo "Repairing the stock vLLM 0.10 wheel files required by FlashAttention..."
    "$NATIVE_PY" -m pip install --no-cache-dir --force-reinstall --no-deps 'vllm==0.10.0'
  fi
  [[ -d "$flash_layers" && -f "$site_packages/vllm/_version.py" ]] || \
    fail "The vLLM 0.10 wheel is missing vllm_flash_attn after repair."
}

build_chiavdf() {
  local source_dir="$NATIVE_SOURCE/shared-utils/chiavdf"
  local work_dir="$NATIVE_BUILD/chiavdf"
  local wheel_dir="$NATIVE_BUILD/chiavdf-wheels"
  if "$NATIVE_PY" -c 'import chiavdf' >/dev/null 2>&1; then
    return 0
  fi
  echo "Building native ChiaVDF with assembly support..."
  rm -rf "$work_dir"
  mkdir -p "$work_dir" "$wheel_dir"
  rsync -a --delete "$source_dir/" "$work_dir/"
  git -C "$work_dir" init -q
  git -C "$work_dir" config user.email 'native-build@tensorcash.local'
  git -C "$work_dir" config user.name 'TensorCash Native Build'
  git -C "$work_dir" add .
  git -C "$work_dir" commit -qm 'Native build source'
  git -C "$work_dir" tag -a v1.0.0 -m 'Version 1.0.0'
  GMP_USE_ASM=1 FLINT_ENABLE_ASM=1 CHIAVDF_NO_ASM='' BUILD_VDF_CLIENT=N \
    PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig \
    "$NATIVE_PY" -m pip wheel "$work_dir" -w "$wheel_dir"
  "$NATIVE_PY" -m pip install "$wheel_dir"/*.whl
  "$NATIVE_PY" -c 'import chiavdf; print("chiavdf native build: OK")'
}

build_proof_processor() {
  local pow_dir="$NATIVE_SOURCE/shared-utils/pow-utils"
  local output="$pow_dir/tests/build/proof_processor.so"
  local site_packages
  site_packages="$($NATIVE_PY -c 'import site; print(site.getsitepackages()[0])')"
  if [[ ! -f "$output" ]]; then
    echo "Building TensorCash C++ proof processor..."
    if [[ ! -f /usr/include/zmq.hpp ]]; then
      as_root wget -q https://raw.githubusercontent.com/zeromq/cppzmq/v4.10.0/zmq.hpp -O /usr/include/zmq.hpp
    fi
    PYTHON_EXEC="$NATIVE_PY" FB_SCHEMAS_DIR="$NATIVE_SOURCE/shared-utils/fb-schemas" \
      bash "$pow_dir/tests/build_proofprocessor_simple.sh"
  fi
  [[ -f "$output" ]] || fail "Proof processor compilation did not produce proof_processor.so."
  install -m 755 "$output" "$site_packages/proof_processor.so"
}

prepare_python_sources() {
  local site_packages generated_python
  site_packages="$($NATIVE_PY -c 'import site; print(site.getsitepackages()[0])')"
  generated_python="$NATIVE_SOURCE/shared-utils/pow-utils/tests/build/generated-python"
  [[ -d "$generated_python/proof" ]] || fail "Generated FlatBuffer proof modules are missing."

  # Keep PoW CDF sampling inside [0, V-1] even when float32 cumsum rounds its
  # terminal boundary below one. The public source ref is intentionally pinned,
  # so this small, audited patch is deterministic and idempotent across resume.
  if ! grep -Fq 'batch_sample_tokens requires a non-empty [B, V] CDF' \
    "$NATIVE_SOURCE/shared-utils/pow-utils/pow_utils.py"; then
    patch --batch --fuzz=2 -d "$NATIVE_SOURCE" -p1 < "$script_dir/native-cdf-tail.patch"
  fi
  grep -Fq 'batch_sample_tokens requires a non-empty [B, V] CDF' \
    "$NATIVE_SOURCE/shared-utils/pow-utils/pow_utils.py" || \
    fail "Native CDF boundary patch was not installed."

  echo "Installing TensorCash vLLM/proxy overlays..."
  repair_stock_vllm_if_needed
  # Deliberately do not add --delete here. TensorCash replaces pure Python
  # files only; the upstream wheel retains native FlashAttention files and
  # vllm._version that are not present in the TensorCash fork.
  rsync -a --exclude='*.so' "$NATIVE_SOURCE/services/miner-api/vllm-v010/vllm/" "$site_packages/vllm/"
  mkdir -p "$site_packages/vllm/sampling/proof"
  rsync -a --delete "$generated_python/proof/" "$site_packages/vllm/sampling/proof/"
  install -m 644 "$NATIVE_SOURCE/shared-utils/pow-utils/common_sampler_helper.py" "$site_packages/vllm/sampling/"
  install -m 644 "$NATIVE_SOURCE/shared-utils/pow-utils/pow_utils.py" "$site_packages/vllm/sampling/"
  install -m 644 "$NATIVE_SOURCE/shared-utils/pow-utils/pow_v3.py" "$site_packages/vllm/sampling/"
  install -m 644 "$NATIVE_SOURCE/shared-utils/pow-utils/bcred_table_r1024.py" "$site_packages/vllm/sampling/"
  install -m 644 "$NATIVE_SOURCE/shared-utils/pow-utils/zmq_pow_writer.py" "$site_packages/vllm/sampling/"
  install -m 644 "$NATIVE_SOURCE/shared-utils/pow-utils/uint256_arithmetics.py" "$site_packages/vllm/sampling/"

  rm -rf "$NATIVE_PROXY"
  mkdir -p "$NATIVE_PROXY"
  rsync -a "$NATIVE_SOURCE/services/miner-api/src/" "$NATIVE_PROXY/"
  mkdir -p "$NATIVE_PROXY/utils" "$NATIVE_PROXY/config" "$NATIVE_PROXY/proof"
  install -m 644 "$NATIVE_SOURCE/shared-utils/pow-utils/pow_utils.py" "$NATIVE_PROXY/utils/"
  install -m 644 "$NATIVE_SOURCE/shared-utils/pow-utils/pow_v3.py" "$NATIVE_PROXY/utils/"
  install -m 644 "$NATIVE_SOURCE/shared-utils/pow-utils/bcred_table_r1024.py" "$NATIVE_PROXY/utils/"
  install -m 644 "$NATIVE_SOURCE/shared-utils/pow-utils/uint256_arithmetics.py" "$NATIVE_PROXY/utils/"
  install -m 644 "$NATIVE_SOURCE/shared-utils/config/constants.py" "$NATIVE_PROXY/config/"
  rsync -a "$generated_python/proof/" "$NATIVE_PROXY/proof/"
  install -m 644 "$script_dir/nomp-sidecar-overlay.py" "$NATIVE_PROXY/components/nomp_sidecar.py"
  install -m 644 "$script_dir/sidecar-status-overlay.py" "$NATIVE_PROXY/sitecustomize.py"
  # Native mode deliberately re-installs this public scheduler overlay on each
  # ordinary launcher run. This makes controller-side fixes (including proof
  # de-duplication under concurrent inference) take effect without rebuilding
  # the Python environment or downloading the model again.
  grep -Fq 'NOMP sidecar dropped duplicate proof' "$NATIVE_PROXY/components/nomp_sidecar.py" || \
    fail "Native NOMP sidecar overlay is missing concurrent-proof de-duplication."
  grep -Fq 'Released superseded TensorCash VDF prover' "$NATIVE_PROXY/sitecustomize.py" || \
    fail "Native NOMP sidecar overlay is missing VDF memory release handling."
  "$NATIVE_PY" -m py_compile "$NATIVE_PROXY/components/nomp_sidecar.py"
  # The public TensorCash source is intentionally NOMP-agnostic.  Apply the
  # small, audited integration patch after copying it so the native proxy has
  # the same authenticated local work-unit routes as the Docker runtime.
  # The official pinned main.py has a generated line-number offset in its
  # upstream diff metadata. The content is immutable at SOURCE_REF; fuzz=2
  # accepts that harmless offset while patch still rejects missing contexts.
  patch --batch --fuzz=2 -d "$NATIVE_PROXY" -p1 < "$script_dir/native-nomp-proxy.patch"
  grep -Fq "app.router.add_post('/v1/tensorcash/jobs'" "$NATIVE_PROXY/main.py" || \
    fail "Native NOMP route patch did not install /v1/tensorcash/jobs."
  grep -Fq "app.router.add_get('/v1/tensorcash/metrics', self.nomp_sidecar.metrics)" "$NATIVE_PROXY/main.py" || \
    fail "Native NOMP route patch did not install /v1/tensorcash/metrics."
  grep -Fq "NOMP_SIDECAR_ENABLED" "$NATIVE_PROXY/components/constants.py" || \
    fail "Native NOMP constants patch was not installed."
}

runtime_marker_is_current() {
  [[ -f "$NATIVE_MARKER" ]] && grep -Fxq "source_ref=$TENSORCASH_SOURCE_REF" "$NATIVE_MARKER" && \
    [[ -x "$NATIVE_VLLM" ]] && [[ -f "$NATIVE_PROXY/main.py" ]] && \
    "$NATIVE_PY" -c 'import chiavdf, proof_processor, vllm; from vllm.vllm_flash_attn.layers import rotary' >/dev/null 2>&1
}

bootstrap_runtime() {
  mkdir -p "$NATIVE_HOME" "$NATIVE_BUILD" "$NATIVE_INSTANCES" "$NATIVE_HOME/capacity"
  chmod 700 "$NATIVE_HOME" "$NATIVE_INSTANCES" "$NATIVE_HOME/capacity"
  if ! "$rebuild" && runtime_marker_is_current; then
    # Keep the launcher-owned sidecar scheduler in sync on every launch.  The
    # expensive wheel/extension build remains cached, but a scheduler update
    # must not wait for miners to rebuild their native environment.
    sync_tensorcash_source
    prepare_python_sources
    echo "Using existing native TensorCash runtime: $NATIVE_HOME"
    return 0
  fi
  install_system_packages
  sync_tensorcash_source
  prepare_python_runtime
  build_chiavdf
  build_proof_processor
  prepare_python_sources
  "$NATIVE_PY" - <<'PY'
import chiavdf
import proof_processor
import torch
import vllm
assert torch.cuda.is_available(), "CUDA is unavailable to PyTorch"
print("Native TensorCash runtime self-test: OK", torch.cuda.get_device_name(0))
PY
  {
    printf 'source_ref=%s\n' "$TENSORCASH_SOURCE_REF"
    printf 'created_utc=%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  } > "$NATIVE_MARKER"
  chmod 600 "$NATIVE_MARKER"
}

model_cache_name() {
  printf '%s' "${MODEL_NAME//\//--}"
}

download_model() {
  local cache_name snapshot marker attempts delay attempt
  cache_name="$(model_cache_name)"
  snapshot="$MODELS_DATA/hub/models--${cache_name}/snapshots/${MODEL_COMMIT}"
  marker="$MODELS_DATA/.tensorcash-model-${cache_name}-${MODEL_COMMIT}.complete"
  attempts="${TENSORCASH_MODEL_DOWNLOAD_ATTEMPTS:-12}"
  delay="${TENSORCASH_MODEL_DOWNLOAD_DELAY_SECONDS:-15}"
  positive_integer "$attempts" TENSORCASH_MODEL_DOWNLOAD_ATTEMPTS
  positive_integer "$delay" TENSORCASH_MODEL_DOWNLOAD_DELAY_SECONDS
  mkdir -p "$MODELS_DATA" "$RUNTIME_DATA"
  chmod 755 "$MODELS_DATA"
  chmod 700 "$RUNTIME_DATA"
  if [[ -f "$marker" && -f "$snapshot/config.json" ]] && compgen -G "$snapshot/*.safetensors" >/dev/null; then
    NATIVE_MODEL_SNAPSHOT="$snapshot"
    return 0
  fi
  for ((attempt = 1; attempt <= attempts; attempt += 1)); do
    echo "Downloading ${MODEL_NAME}@${MODEL_COMMIT} (attempt $attempt/$attempts; cache resumes after interruption)..."
    if MODEL_NAME="$MODEL_NAME" MODEL_COMMIT="$MODEL_COMMIT" MODELS_DATA="$MODELS_DATA" \
      HTTP_PROXY="${TENSORCASH_HTTP_PROXY:-${HTTP_PROXY:-}}" HTTPS_PROXY="${TENSORCASH_HTTP_PROXY:-${HTTPS_PROXY:-}}" \
      "$NATIVE_PY" - <<'PY'
import os
from huggingface_hub import snapshot_download
snapshot_download(
    repo_id=os.environ["MODEL_NAME"],
    revision=os.environ["MODEL_COMMIT"],
    cache_dir=os.path.join(os.environ["MODELS_DATA"], "hub"),
)
PY
    then
      break
    fi
    (( attempt < attempts )) || fail "Pinned model download failed after $attempts attempts."
    echo "Model download interrupted; retrying in ${delay}s with the existing cache..." >&2
    sleep "$delay"
  done
  [[ -f "$snapshot/config.json" ]] || fail "Model cache lacks config.json after download."
  compgen -G "$snapshot/*.safetensors" >/dev/null || fail "Model cache lacks safetensors weights after download."
  {
    printf 'model=%s\n' "$MODEL_NAME"
    printf 'commit=%s\n' "$MODEL_COMMIT"
    printf 'completed_utc=%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  } > "$marker"
  chmod 600 "$marker"
  NATIVE_MODEL_SNAPSHOT="$snapshot"
}

pid_file() { printf '%s/%s.pid\n' "$NATIVE_PIDS" "$1"; }

pid_running() {
  local file
  file="$(pid_file "$1")"
  [[ -f "$file" ]] || return 1
  kill -0 "$(<"$file")" 2>/dev/null
}

stop_process() {
  local name="$1" file pid
  file="$(pid_file "$name")"
  [[ -f "$file" ]] || return 0
  pid="$(<"$file")"
  if kill -0 "$pid" 2>/dev/null; then
    echo "Stopping native $name (PID $pid)..."
    kill -TERM "$pid" 2>/dev/null || true
    for _ in {1..30}; do
      kill -0 "$pid" 2>/dev/null || break
      sleep 1
    done
    kill -0 "$pid" 2>/dev/null && kill -KILL "$pid" 2>/dev/null || true
  fi
  rm -f "$file"
}

stop_instance() {
  stop_process miner
  stop_process proxy
  stop_process vllm
}

legacy_instance_paths() {
  NATIVE_INSTANCE='legacy'
  NATIVE_INSTANCE_HOME="$NATIVE_HOME"
  NATIVE_LOGS="$NATIVE_HOME/logs"
  NATIVE_PIDS="$NATIVE_HOME/pids"
  NATIVE_INSTANCE_ENV="$NATIVE_HOME/runtime.env"
}

stop_all() {
  local instance
  native_paths
  # Native versions before multi-GPU support stored a single group's files
  # directly under runtime/native. Stop it too during migration.
  legacy_instance_paths
  stop_instance
  for instance in "$NATIVE_INSTANCES"/g*; do
    [[ -d "$instance" ]] || continue
    native_instance_paths "$(basename "$instance")"
    stop_instance
  done
}

show_instance_status() {
  local name file pid sidecar_port
  printf '=== native TensorCash %s ===\n' "$NATIVE_INSTANCE"
  for name in vllm proxy miner; do
    file="$(pid_file "$name")"
    if pid_running "$name"; then
      pid="$(<"$file")"
      printf '%-6s running (pid %s)\n' "$name" "$pid"
    else
      printf '%-6s stopped\n' "$name"
    fi
  done
  sidecar_port="$(sed -n 's/^HTTP_PORT=//p' "$NATIVE_INSTANCE_ENV" 2>/dev/null | tail -n 1)"
  [[ "$sidecar_port" =~ ^[0-9]+$ ]] || sidecar_port=8080
  printf 'sidecar '
  curl -fsS "http://127.0.0.1:${sidecar_port}/health" 2>/dev/null || echo 'unavailable'
}

show_native_status() {
  native_paths
  local instance found=false
  for instance in "$NATIVE_INSTANCES"/g*; do
    [[ -d "$instance" ]] || continue
    found=true
    native_instance_paths "$(basename "$instance")"
    show_instance_status
  done
  if ! "$found"; then
    legacy_instance_paths
    show_instance_status
  fi

  if command -v nvidia-smi >/dev/null 2>&1; then
    echo "=== GPU ==="
    nvidia-smi --query-gpu=index,name,pstate,power.draw,utilization.gpu,memory.used,memory.total \
      --format=csv,noheader
  fi
}

show_native_plan() {
  local index number=0 memory gpu_name capacity_file
  local -a gpu_indices=()
  mapfile -t gpu_indices < <(resolve_native_gpu_indices)
  echo "=== native TensorCash TP=1 launch plan ==="
  for index in "${gpu_indices[@]}"; do
    number=$((number + 1))
    memory="$(nvidia-smi --id="$index" --query-gpu=memory.total --format=csv,noheader,nounits | tr -d '[:space:]')"
    gpu_name="$(nvidia-smi --id="$index" --query-gpu=name --format=csv,noheader | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    capacity_file="$(native_capacity_file "$gpu_name" "$memory")"
    printf 'g%s: GPU %s (%s, %s MiB) -> vLLM=%s sidecar=%s proof=%s capacity=%s\n' \
      "$number" "$index" "$gpu_name" "$memory" "$((8000 + number - 1))" \
      "$((8080 + number - 1))" "$((7002 + number - 1))" "$capacity_file"
  done
}

wait_for_http() {
  local url="$1" seconds="$2" title="$3"
  local elapsed=0
  while (( elapsed < seconds )); do
    curl -fsS "$url" >/dev/null 2>&1 && return 0
    sleep 2
    elapsed=$((elapsed + 2))
  done
  echo "=== $title log ===" >&2
  tail -n 100 "$NATIVE_LOGS/${title}.log" >&2 || true
  fail "$title did not become ready within ${seconds}s."
}

wait_for_vllm_capacity() {
  local file="$1" seconds="$2" requested="$3"
  local elapsed=0 value
  while (( elapsed < seconds )); do
    if [[ -r "$file" ]]; then
      IFS= read -r value < "$file" || true
      if [[ "${value:-}" =~ ^[1-9][0-9]*$ ]] && (( value <= requested )); then
        printf '%s\n' "$value"
        return 0
      fi
    fi
    if ! pid_running vllm; then
      echo '=== vllm log ===' >&2
      tail -n 100 "$NATIVE_LOGS/vllm.log" >&2 || true
      fail 'Native vLLM exited before its capacity probe completed.'
    fi
    sleep 2
    elapsed=$((elapsed + 2))
  done
  echo '=== vllm log ===' >&2
  tail -n 100 "$NATIVE_LOGS/vllm.log" >&2 || true
  fail "Native vLLM did not finish its capacity probe within ${seconds}s."
}

native_instance_token() {
  local instance="$1"
  printf '%s' "${NOMP_SIDECAR_TOKEN}:${instance}" | sha256sum | awk '{print $1}'
}

seed_profile_capacity_from_legacy() {
  local destination="$1" minimum="$2" legacy="$RUNTIME_DATA/native/vllm-effective-max-seqs" value
  [[ ! -r "$destination" && -r "$legacy" ]] || return 0
  IFS= read -r value < "$legacy" || return 0
  [[ "$value" =~ ^[1-9][0-9]*$ ]] || return 0
  (( value >= minimum && value <= VLLM_MAX_NUM_SEQS )) || return 0
  mkdir -p "$(dirname "$destination")"
  umask 077
  printf '%s\n' "$value" > "$destination"
  echo "Reusing legacy GPU0 bootstrap-confirmed max sequences=$value for this matching hardware profile."
}

start_native_instance() {
  local instance_number="$1" gpu_index="$2"
  local memory gpu_name env_file vllm_effective_file vllm_fallback_min effective_max_seqs
  local instance_data vllm_port sidecar_port collector_port sidecar_token group_worker
  local cache_name
  native_instance_paths "g$instance_number"
  memory="$(nvidia-smi --id="$gpu_index" --query-gpu=memory.total --format=csv,noheader,nounits | tr -d '[:space:]')"
  gpu_name="$(nvidia-smi --id="$gpu_index" --query-gpu=name --format=csv,noheader | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
  [[ "$memory" =~ ^[0-9]+$ && -n "$gpu_name" ]] || fail "GPU $gpu_index is not visible to nvidia-smi."
  (( memory >= ${TENSORCASH_NATIVE_MIN_VRAM_MIB:-22000} )) || fail "Native TP=1 needs >=${TENSORCASH_NATIVE_MIN_VRAM_MIB:-22000} MiB VRAM; GPU $gpu_index exposes ${memory} MiB."
  if [[ "$TENSORCASH_CONCURRENCY_MODE" == auto ]]; then
    configure_native_auto_concurrency "$memory"
    echo "Native $NATIVE_INSTANCE auto concurrency: start=${NOMP_SIDECAR_ADAPTIVE_START_CONCURRENCY}, cap=${VLLM_MAX_NUM_SEQS}, step=${NOMP_SIDECAR_ADAPTIVE_STEP}, prefetch=${NOMP_SIDECAR_PREFETCH_REQUESTS}"
  fi
  if [[ "$TENSORCASH_CONCURRENCY_MODE" == manual ]]; then
    (( VLLM_MAX_NUM_SEQS >= NOMP_SIDECAR_CONCURRENCY )) || fail "VLLM_MAX_NUM_SEQS must cover NOMP_SIDECAR_CONCURRENCY."
  fi
  vllm_effective_file="$(native_capacity_file "$gpu_name" "$memory")"
  vllm_fallback_min="$VLLM_MAX_NUM_SEQS"
  if [[ "$TENSORCASH_CONCURRENCY_MODE" == auto ]]; then
    vllm_fallback_min="$NOMP_SIDECAR_ADAPTIVE_START_CONCURRENCY"
  fi
  # The single-GPU native layout used this location before profile-keyed
  # capacity reuse existed. Preserve a valid first-card discovery across the
  # launcher upgrade so a same-model multi-card host does not pay it twice.
  (( instance_number == 1 )) && seed_profile_capacity_from_legacy "$vllm_effective_file" "$vllm_fallback_min"
  cache_name="$(model_cache_name)"
  instance_data="$RUNTIME_DATA/native/$NATIVE_INSTANCE"
  native_allocate_instance_ports "$instance_number"
  vllm_port="$NATIVE_VLLM_PORT"
  sidecar_port="$NATIVE_SIDECAR_PORT"
  collector_port="$NATIVE_COLLECTOR_PORT"
  sidecar_token="$(native_instance_token "$NATIVE_INSTANCE")"
  group_worker="${WORKER}-${NATIVE_INSTANCE}"

  mkdir -p "$NATIVE_LOGS" "$NATIVE_PIDS" "$instance_data"
  chmod 700 "$NATIVE_INSTANCE_HOME" "$NATIVE_LOGS" "$NATIVE_PIDS" "$instance_data"
  env_file="$NATIVE_INSTANCE_ENV"
  umask 077
  cat > "$env_file" <<EOF
PYTHONPATH=$NATIVE_PROXY
LD_LIBRARY_PATH=/usr/local/lib:/usr/lib/x86_64-linux-gnu
CUDA_VISIBLE_DEVICES=$gpu_index
MODEL_NAME=$MODEL_NAME
MODEL_COMMIT=$MODEL_COMMIT
MODEL_DIFFICULTY_NORMALIZER=$MODEL_DIFFICULTY_NORMALIZER
MAX_MODEL_LEN=$MAX_MODEL_LEN
GPU_MEM_UTIL=$GPU_MEM_UTIL
VLLM_MAX_NUM_SEQS=$VLLM_MAX_NUM_SEQS
VLLM_PORT=$vllm_port
VLLM_CUDA_GRAPH_SIZES=${VLLM_CUDA_GRAPH_SIZES:-}
VLLM_MAX_NUM_BATCHED_TOKENS=${VLLM_MAX_NUM_BATCHED_TOKENS:-}
VLLM_MODEL_PATH=$NATIVE_MODEL_SNAPSHOT
CHAT_TEMPLATE_PATH=$NATIVE_SOURCE/deployments/simple-worker/chat-template/qwen3.5-enhanced.jinja
TENSORCASH_VLLM_EFFECTIVE_MAX_SEQS_FILE=$vllm_effective_file
TENSORCASH_VLLM_FALLBACK_MIN_SEQS=$vllm_fallback_min
TENSORCASH_VLLM_STARTUP_TIMEOUT_SECONDS=${TENSORCASH_VLLM_STARTUP_TIMEOUT_SECONDS:-900}
NOMP_SIDECAR_TOKEN=$sidecar_token
NOMP_SIDECAR_ENABLED=true
NOMP_SIDECAR_CONCURRENCY=$NOMP_SIDECAR_CONCURRENCY
NOMP_SIDECAR_ADAPTIVE_START_CONCURRENCY=${NOMP_SIDECAR_ADAPTIVE_START_CONCURRENCY:-}
NOMP_SIDECAR_ADAPTIVE_MAX_CONCURRENCY=${NOMP_SIDECAR_ADAPTIVE_MAX_CONCURRENCY:-}
NOMP_SIDECAR_ADAPTIVE_STEP=${NOMP_SIDECAR_ADAPTIVE_STEP:-}
NOMP_SIDECAR_MIN_BUFFERED_PROOFS=$NOMP_SIDECAR_MIN_BUFFERED_PROOFS
NOMP_SIDECAR_MAX_BUFFERED_PROOFS=$NOMP_SIDECAR_MAX_BUFFERED_PROOFS
TENSORCASH_SUBMIT_WINDOW=$TENSORCASH_SUBMIT_WINDOW
MINING_SOLUTION_COOLDOWN_SEC=0
WORKER_MODE=standalone
STANDALONE_MODE=true
HTTP_HOST=127.0.0.1
HTTP_PORT=$sidecar_port
TARGET_URL=http://127.0.0.1:$vllm_port
API_KEY=internal-secret
TEST_MODE=false
PRIORITY_MODE=false
MIN_ACTIVE_REQUESTS=0
MINING_ENABLED=true
POW_PROOF_VERSION=3
PROOF_CACHE_ENABLED=false
PROOF_COLLECTOR_PORT=$collector_port
TOOL_CALL_PARSER=qwen3_coder
USE_VLLM_XARGS=false
HF_HOME=$MODELS_DATA
HF_HUB_CACHE=$MODELS_DATA/hub
TRANSFORMERS_CACHE=$MODELS_DATA/hub
HF_MODULES_CACHE=$instance_data/hf-modules
HF_HUB_OFFLINE=1
TRANSFORMERS_OFFLINE=1
HF_HUB_DISABLE_TELEMETRY=1
VLLM_ENABLE_POW=1
POW_EGRESS_MODE=broker
POW_PROXY_ENABLE=false
ZMQ_PUSH_HOST=127.0.0.1
ZMQ_PUSH_PORT=$collector_port
POW_PROCESSOR_MODE=cpp
VLLM_ENABLE_RESPONSES_API_STORE=1
VLLM_DO_NOT_TRACK=1
TENSORCASH_VLLM_CLEANUP_GPU_IDS=$gpu_index
EOF
  if [[ -n "${NOMP_SIDECAR_ADMISSION_SPREAD_MS:-}" ]]; then
    printf 'NOMP_SIDECAR_ADMISSION_SPREAD_MS=%s\n' \
      "$NOMP_SIDECAR_ADMISSION_SPREAD_MS" >> "$env_file"
  fi
  if [[ -n "${NOMP_SIDECAR_PREFETCH_REQUESTS:-}" ]]; then
    printf 'NOMP_SIDECAR_PREFETCH_REQUESTS=%s\n' \
      "$NOMP_SIDECAR_PREFETCH_REQUESTS" >> "$env_file"
  fi
  chmod 600 "$env_file"

  echo "Starting native TensorCash $NATIVE_INSTANCE on GPU $gpu_index (${gpu_name}, ${memory} MiB), requested max sequences=$VLLM_MAX_NUM_SEQS..."
  (
    set -a
    source "$env_file"
    set +a
    export VLLM_BIN="$NATIVE_VLLM"
    export VLLM_HOST=127.0.0.1
    export VLLM_PORT="$vllm_port"
    export VLLM_HEALTH_URL="http://127.0.0.1:${vllm_port}/health"
    export VLLM_CDF_PATCH_PATH=''
    export VLLM_BOOT_LOG=''
    exec bash "$script_dir/vllm-local-cache.sh"
  ) >"$NATIVE_LOGS/vllm.log" 2>&1 &
  echo $! > "$(pid_file vllm)"
  effective_max_seqs="$(wait_for_vllm_capacity \
    "$vllm_effective_file" 1800 "$VLLM_MAX_NUM_SEQS")"
  wait_for_http "http://127.0.0.1:${vllm_port}/health" 120 vllm
  printf '\n# Written by the vLLM bootstrap capacity probe.\nVLLM_MAX_NUM_SEQS=%s\n' \
    "$effective_max_seqs" >> "$env_file"
  echo "Native $NATIVE_INSTANCE vLLM bootstrap-confirmed max sequences=$effective_max_seqs"

  echo "Starting native TensorCash sidecar..."
  (
    set -a
    source "$env_file"
    set +a
    cd "$NATIVE_PROXY"
    exec "$NATIVE_PY" main.py
  ) >"$NATIVE_LOGS/proxy.log" 2>&1 &
  echo $! > "$(pid_file proxy)"
  wait_for_http "http://127.0.0.1:${sidecar_port}/health" 300 proxy

  echo "Starting TensorCash controller..."
  (
    set -a
    source "$env_file"
    set +a
    exec "$script_dir/runtime/bin/niuquanminer" \
      --algo tensorcash --pool "$POOL_HOST" --port "$POOL_PORT" \
      --wallet "$PAYOUT_ACCOUNT" --worker "$group_worker" \
      --tensorcash-sidecar "http://127.0.0.1:${sidecar_port}" \
      --tensorcash-sidecar-token "$sidecar_token" \
      --tensorcash-poll-ms "$TENSORCASH_POLL_MS" \
      --tensorcash-submit-window "$TENSORCASH_SUBMIT_WINDOW" \
      --stats-interval "$TENSORCASH_STATS_INTERVAL"
  ) >"$NATIVE_LOGS/miner.log" 2>&1 &
  echo $! > "$(pid_file miner)"
  sleep 2
  pid_running miner || { tail -n 100 "$NATIVE_LOGS/miner.log" >&2 || true; fail "TensorCash controller exited immediately."; }
  echo "Native TensorCash $NATIVE_INSTANCE started: GPU $gpu_index, vLLM=$vllm_port, sidecar=$sidecar_port."
  echo "Logs: $NATIVE_LOGS/{vllm,proxy,miner}.log"
}

start_native() {
  local index number=0
  local -a gpu_indices=()
  mapfile -t gpu_indices < <(resolve_native_gpu_indices)
  echo "Native TensorCash selected TP=1 GPU groups: $(IFS=,; printf '%s' "${gpu_indices[*]}")"
  stop_all
  NATIVE_RESERVED_PORTS=''
  for index in "${gpu_indices[@]}"; do
    number=$((number + 1))
    start_native_instance "$number" "$index"
  done
  echo "Native TensorCash started ${#gpu_indices[@]} independent TP=1 group(s)."
}

while (($#)); do
  case "$1" in
    --pool) pool_arg="${2:-}"; shift 2 ;;
    --wallet) wallet_arg="${2:-}"; shift 2 ;;
    --worker) worker_arg="${2:-}"; shift 2 ;;
    --gpu) gpu_arg="${2:-}"; shift 2 ;;
    --install) install_only=true; shift ;;
    --rebuild-runtime) rebuild=true; shift ;;
    --stop) stop_only=true; shift ;;
    --status) status_only=true; shift ;;
    --plan) plan_only=true; shift ;;
    --logs) logs_only=true; shift ;;
    --purge-runtime) purge_only=true; shift ;;
    --help|-h) usage; exit 0 ;;
    *) fail "Unknown option: $1" ;;
  esac
done

if "$stop_only"; then
  stop_all
  exit 0
fi
if "$purge_only"; then
  native_paths
  stop_all
  rm -rf "$NATIVE_HOME"
  echo "Deleted script-owned native runtime: $NATIVE_HOME"
  exit 0
fi
if "$logs_only"; then
  log_files=()
  native_paths
  for instance_dir in "$NATIVE_INSTANCES"/g*; do
    [[ -d "$instance_dir/logs" ]] || continue
    log_files+=("$instance_dir/logs/miner.log" "$instance_dir/logs/proxy.log" "$instance_dir/logs/vllm.log")
  done
  if ((${#log_files[@]} == 0)); then
    # Preserve access to logs from the pre-multi-GPU native layout.
    mkdir -p "$NATIVE_HOME/logs"
    log_files=("$NATIVE_HOME/logs/miner.log" "$NATIVE_HOME/logs/proxy.log" "$NATIVE_HOME/logs/vllm.log")
  fi
  tail -n 100 -f "${log_files[@]}"
  exit 0
fi
if "$status_only"; then
  show_native_status
  exit 0
fi

require_command bash
require_command curl
require_command git
require_command nvidia-smi
require_command sha256sum
require_command rsync
load_config
native_paths
if "$plan_only"; then
  show_native_plan
  exit 0
fi
bootstrap_runtime
ensure_compatible_miner_binary
if "$install_only"; then
  echo "Native TensorCash runtime is ready. Start it with: bash native-vast.sh"
  exit 0
fi
download_model
start_native
